/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef WML_H
#define WML_H

#ifdef _WIN32
#define WML_EXPORT_FUNC __declspec(dllexport)
#else
#define WML_EXPORT_FUNC
#endif

#include <string>

namespace WML {
    class Greeter {
        public:
        std::string WML_EXPORT_FUNC greeting();
    };
}

#endif
