/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "WML.h"

std::string WML::Greeter::greeting() {
    return std::string("Hello, World!");
}
